--import libri--
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Herman Melville ', 5, '"Moby Dick" is an epic novel written by Herman Melville in 1851. The story follows the adventures of the young sailor Ishmael and Captain Ahab aboard the whaling ship Pequod. Ahab is obsessed with hunting the white whale, Moby Dick, which had previously maimed him and driven him mad. The narrative explores themes of obsession, revenge, and fate as the Pequod sails through perilous seas and encounters with other whaling ships. Ultimately, the hunt leads to a violent confrontation between Ahab and Moby Dick, with dramatic consequences for the crew. The novel is widely regarded as a masterpiece of American literature, known for its narrative complexity and profound reflections on human nature and the forces of life and death.', 'https://m.media-amazon.com/images/I/71d5wo+-MuL._AC_UF1000,1000_QL80_.jpg', 10.50, 'Moby Dick');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('J.K Rowling ', 4, '"Harry Potter and the Prisoner of Azkaban" is the third novel in the "Harry Potter" series written by J.K. Rowling. The story begins with Harry returning to the Hogwarts School of Witchcraft and Wizardry for his third year. This year, the school is threatened by a dangerous fugitive, Sirius Black, who is believed to be involved in the death of Harry\'s parents. With the help of his friends Ron and Hermione, Harry uncovers the truth about Sirius and his connection to his past. Meanwhile, he is introduced to the Dark Wizard Lord Voldemort. The novel explores themes of friendship, courage, and the concept of justice as Harry confronts his inner demons and prepares to face his destiny.', 'https://m.media-amazon.com/images/I/91VZqV0Cy8L._AC_UF1000,1000_QL80_.jpg', 12.50, 'Harry Potter - Prisoner of Azkaban');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('J.K Rowling ', 2, '"Harry Potter and the Deathly Hallows" is the seventh and final novel in the "Harry Potter" series written by J.K. Rowling. The story follows Harry Potter, Ron Weasley, and Hermione Granger as they seek to destroy the Horcruxes, objects in which the Dark Lord Voldemort has hidden fragments of his soul to ensure his immortality. As the war between good and evil reaches its climax, Harry discovers the truth about his connection to Voldemort and the fate that awaits him. Through sacrifices and courage, Harry and his friends confront their greatest enemy in an epic final showdown. The novel explores themes of love, forgiveness, sacrifice, and the power of hope as the characters face their destiny and the meaning of true courage.', 'https://m.media-amazon.com/images/I/81W7uynFyWL._AC_UF1000,1000_QL80_.jpg', 13, 'Harry Potter - Deathly Hallows');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('J.K Rowling ', 3, '"Harry Potter and the Order of the Phoenix" is the fifth book in J.K. Rowling\'s "Harry Potter" series. The story follows Harry\'s tumultuous fifth year at Hogwarts School of Witchcraft and Wizardry. As Harry returns to school, he discovers that the wizarding world is in denial about Lord Voldemort\'s return, and the Ministry of Magic is actively working to discredit him and Professor Dumbledore. Harry, along with his friends Ron and Hermione, forms "Dumbledore\'s Army" to teach fellow students defensive spells in secret. Meanwhile, Harry faces internal struggles as he grapples with visions and dreams linked to Voldemort\'s mind. The novel delves into themes of rebellion, friendship, and the challenges of adolescence as Harry and his peers navigate the growing darkness threatening their world.', 'https://m.media-amazon.com/images/I/813lOXWdSNL._AC_UF1000,1000_QL80_.jpg', 14, 'Harry Potter - Order of Phoenix');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('J.K Rowling', 4, '"Harry Potter and the Half-Blood Prince" is the sixth book in J.K. Rowling\'s "Harry Potter" series. The story continues Harry\'s journey as a wizard, focusing on his sixth year at Hogwarts School of Witchcraft and Wizardry. As Harry prepares for his final confrontation with Lord Voldemort, he learns more about the Dark Lord\'s past and the significance of Horcruxes—objects containing fragments of Voldemort\'s soul. With the help of Professor Dumbledore, Harry delves into memories of Voldemort\'s youth to uncover crucial information. Meanwhile, Hogwarts is facing new threats as tensions rise within the wizarding world. The novel explores themes of love, loss, and the choices that shape one\'s destiny as Harry and his friends confront the challenges ahead.', 'https://m.media-amazon.com/images/I/81YvqjX4AdL._SY466_.jpg', 13, 'Harry Potter - Half-Blood Prince');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Robert C. Martin ', 5, '"Clean Code" is a book written by Robert C. Martin, also known as "Uncle Bob," which focuses on the importance of writing clean and readable code. Martin presents principles and practices for writing code that is easy to understand, modify, and maintain over time. The book offers practical advice on naming variables, writing functions and classes, managing complexity, and more. Through code examples and case studies, Martin demonstrates the importance of writing clear and well-structured code to improve the overall quality of software.', 'https://m.media-amazon.com/images/I/51E2055ZGUL._SY466_.jpg', 29, 'Clean Code');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('George Orwell ', 5, '"1984" is a dystopian novel written by George Orwell in 1949. Set in a totalitarian world controlled by the Party and its leader, Big Brother, the novel follows the life of Winston Smith, a man who works at the Ministry of Truth. Winston begins to question the oppressive regime he lives under and rebels against the Party\'s manipulation. In an attempt to resist the state\'s total control, Winston begins a forbidden relationship with Julia, another rebel. However, the rebellion is swiftly suppressed, and the two are subjected to brutal treatment by the Party. The novel explores themes of government control, media manipulation, loss of individual freedom, and the power of human resistance.','https://m.media-amazon.com/images/I/81StSOpmkjL._AC_UF1000,1000_QL80_.jpg',11.99,'1984');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('J.K Rowling ', 4, '"Harry Potter and the Philosopher\'s Stone" introduces readers to Harry Potter, an orphaned boy who learns on his eleventh birthday that he is a wizard. He is invited to attend Hogwarts School of Witchcraft and Wizardry, where he discovers a world of magic, friendship, and adventure. Harry makes friends with Ron Weasley and Hermione Granger, and together they uncover the mystery of the Philosopher\'s Stone, an object that grants immortality. Throughout the school year, Harry learns about his past, his parents\' legacy, and the dark wizard Voldemort, who tried to kill him as a baby. The novel explores themes of friendship, courage, and the power of love as Harry confronts the challenges of being the Boy Who Lived and embarks on his journey to defeat Voldemort.','https://libreriavitaepensiero.mediabiblos.it/copertine/salani/harry-potter-e-la-pietra-filosofale-ediz-anniversario-25-anni-9788831017329.jpg',9.50,'Harry Potter - Philosopher\'s stone');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('J.K Rowling ', 3, '"Harry Potter and the Chamber of Secrets" follows Harry\'s second year at Hogwarts School of Witchcraft and Wizardry. As Harry returns to school, mysterious events start occurring, including students being petrified by a creature thought to be the mythical Chamber of Secrets. Harry, along with his friends Ron and Hermione, investigates the Chamber\'s history and uncovers dark secrets hidden within Hogwarts. Throughout the school year, Harry faces challenges, encounters new magical creatures, and learns more about his own abilities. The novel delves into themes of prejudice, loyalty, and the consequences of dark magic as Harry confronts the true identity of the heir of Slytherin and the monster lurking in the Chamber of Secrets.','https://m.media-amazon.com/images/I/81gOJoEgVoL._AC_UF1000,1000_QL80_.jpg',10.75,'Harry Potter - Chamber of secrets');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('J.K Rowling ', 4, '"Harry Potter and the Goblet of Fire" sees Harry returning to Hogwarts for his fourth year, only to find himself unexpectedly entered into the dangerous Triwizard Tournament, a competition between three wizarding schools. As Harry navigates the challenges of the tournament, including facing deadly tasks, he also uncovers a plot involving Lord Voldemort\'s return to power. The novel explores themes of friendship, betrayal, and the consequences of choices as Harry grapples with his destiny and the rising threat of Voldemort\'s return. Alongside his friends Ron and Hermione, Harry faces increasingly dangerous situations, culminating in a shocking climax that sets the stage for the battles to come in the wizarding world.','https://m.media-amazon.com/images/I/81sUIr3c1pL._AC_UF1000,1000_QL80_.jpg',13.95,'Harry potter - Goblet of fire');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Judith Kerr ', 3, '"Quando Hitler rubò il coniglio rosa" is a semi-autobiographical novel written by Judith Kerr. The story follows the life of Anna, a young Jewish girl, and her family as they flee from Nazi Germany to England during World War II. The novel explores the trauma and loss that the family faces during their escape and their struggle to adapt to a new life in a foreign country. Through Anna\'s eyes, the reader is taken on an emotional journey that addresses themes of identity, belonging, and resilience in times of great historical turmoil.','https://www.leggendoleggendo.it/wp-content/uploads/2020/01/9788817154369.jpg',8.40,'Quando Hitler rubò il coniglio rosa');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Lewis Carroll ', 5, '"Alice\'s Adventures in Wonderland" follows the story of a young girl named Alice who falls down a rabbit hole into a fantastical world. In this strange land, Alice encounters peculiar creatures such as the White Rabbit, the Cheshire Cat, and the Mad Hatter, each with their own quirks and riddles. As she navigates through Wonderland, Alice encounters bizarre situations and challenges, often defying logic and reason. The novel is a whimsical and surreal journey filled with wordplay, absurdity, and fantastical imagery. Through her adventures, Alice learns valuable lessons about curiosity, identity, and the nature of reality.','https://m.media-amazon.com/images/I/711cPWrJXRL._AC_UF1000,1000_QL80_.jpg',29.90,'Alice\'s adventures in Wonderland');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Dan Brown ', 5, '"The Da Vinci Code" by Dan Brown is a gripping mystery thriller that follows the adventures of symbologist Robert Langdon and cryptologist Sophie Neveu as they unravel a series of cryptic clues left behind by a murdered curator at the Louvre Museum in Paris. As they race against time, Langdon and Neveu uncover a secret society, the Priory of Sion, and its connection to a controversial theory about the true identity of Mary Magdalene and the existence of a hidden bloodline. Their quest takes them across Europe, from Paris to London, as they evade pursuit by both the police and a clandestine organization determined to protect the centuries-old secret at all costs. Filled with twists, historical intrigue, and religious symbolism, "The Da Vinci Code" keeps readers on the edge of their seats until the very end.','https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1463592438i/30228538.jpg',14.72,'The Da Vinci code');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('José Saramago ', 5, '"Cecità"  by José Saramago is a novel that explores the social and emotional consequences of a mysterious epidemic of sudden blindness that strikes an unnamed city. The book follows the lives of the characters as they are suddenly deprived of sight and are quarantined in an abandoned hospital. As the situation becomes increasingly desperate and society begins to collapse, dynamics of survival, power, and dehumanization emerge. The novel offers a profound reflection on human nature and society, exploring themes of fear, solidarity, selfishness, and hope in a world on the brink of collapse.','https://www.ibs.it/images/9788858831939_0_536_0_75.jpg',11.40,'Cecità');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Stephen King ', 4, '"It" by Stephen King is a horror novel that tells the story of a group of childhood friends who are reunited as adults to confront a terrifying evil that has haunted their hometown for centuries. The evil entity, known as Pennywise the Dancing Clown, resurfaces every twenty-seven years to prey on the children of Derry, Maine. As the group, known as the Losers\' Club, faces their deepest fears and confronts their traumatic memories, they must band together to defeat It once and for all. The novel alternates between the characters\' experiences as children in the 1950s and as adults in the 1980s, intertwining themes of friendship, courage, and the power of belief in the face of unspeakable horrors.','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/It_%281986%29_front_cover%2C_first_edition.jpg/800px-It_%281986%29_front_cover%2C_first_edition.jpg',17.95,'It');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Bram Stoker ', 4, '"Dracula" by Bram Stoker is a Gothic horror novel that tells the story of Count Dracula\'s attempt to move from Transylvania to England so that he may find new blood and spread the undead curse. The novel is presented as a collection of diary entries, letters, and newspaper articles, offering multiple perspectives on the events unfolding. As Dracula\'s sinister influence spreads, a group of people, including Jonathan Harker, Mina Murray, and Professor Abraham Van Helsing, come together to thwart his evil plans. They embark on a quest to stop Dracula before he can unleash his reign of terror upon England. Filled with themes of superstition, sexuality, and the struggle between good and evil, "Dracula" remains a classic tale of horror and suspense.','https://m.media-amazon.com/images/I/61w70l39W9L._AC_UF1000,1000_QL80_.jpg',17.10,'Dracula');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('H.P. Lovecraft ', 5, '"The Call of Cthulhu" is a short story by H.P. Lovecraft, considered a seminal work in the genre of cosmic horror. The story is presented as a manuscript written by the protagonist, who investigates a series of mysterious events following the death of his great-uncle, Professor George Gammell Angell. The narrative explores the discovery of ancient cults, forbidden knowledge, and the awakening of cosmic entities beyond human comprehension. The central figure in the story is Cthulhu, a monstrous and ancient deity that lies dormant beneath the sea. As the protagonist delves deeper into the secrets surrounding Cthulhu and the cult that worships it, he uncovers a terrifying truth about humanity\'s place in the universe and the fragility of sanity in the face of cosmic horrors.','https://m.media-amazon.com/images/I/71HrG7nN14L._AC_UF1000,1000_QL80_.jpg',5.60,'The Call of Cthulhu');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Mary Shelley ', 3, '"Frankenstein" by Mary Shelley tells the story of Victor Frankenstein, a young scientist who becomes obsessed with the idea of creating life. Using various scientific methods, Victor successfully brings to life a creature made from discarded body parts. However, horrified by his creation\'s monstrous appearance, Victor abandons it. The Creature, left to fend for itself in a world that rejects it, seeks revenge against its creator. As the novel unfolds, it explores themes of ambition, scientific ethics, and the consequences of unchecked pursuit of knowledge. Through the Creature\'s experiences and Victor\'s moral dilemmas, "Frankenstein" raises profound questions about what it means to be human and the responsibilities that come with wielding power over life and death.','https://www.newtoncompton.com/files/cache/bookimages/17250/frankenstein-x1000.jpg',8.08,'Frankenstein');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Michael McDowell ', 4, '"The Golden Needles" by Michael McDowell is the first book in the gothic saga "Blackwater." Set in the town of Perdido, Alabama, the book follows the story of the powerful and mysterious Caskey family and their intricate relationships. When Elinor Dammert, a young and ambitious woman, arrives in Perdido, she marries the wealthy and influential patriarch of the Caskey family, Carr Caskey. However, Elinor\'s seemingly idyllic life is disrupted by dark secrets, vendettas, and family tragedies that date back generations. With an intricate plot and complex characters, the novel explores themes of power, inheritance, and the dark side of human nature in a gothic and atmospheric setting.','https://www.ibs.it/images/9788854529199_0_424_0_75.jpg',14.90,'Gli aghi d\'oro');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Jason Rekulak ', 5, '"Hidden Pictures" by Jason Rekulak is a captivating novel that follows the story of a young girl named Wren, living in the 1980s. Set in a small town, the book explores her inner world as she grapples with the changes of adolescence. When she discovers a series of mysterious photographs hidden in her father\'s photo development shop, Wren embarks on an adventure to uncover the secrets behind them. The novel tackles themes of growth, self-discovery, and the power of images to capture and conceal deep truths. With engaging storytelling and well-developed characters, "Hidden Pictures" offers an exciting journey through Wren\'s past and present. ','https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/91puw8POkwL._SY466_.jpg',14.90,'Hidden Pictures: A Novel');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Richard Matheson ', 5, '"I Am Legend" by Richard Matheson is a dystopian novel that follows the story of Robert Neville, the last man on Earth after a virus has turned most of humanity into vampires. Neville struggles to survive, avoiding vampires during the day and searching for a cure for the virus at night. The story explores themes of loneliness, survival, and humanity as Neville desperately seeks a reason to keep living in a world that seems entirely against him.','https://www.ibs.it/images/9788804723974_0_536_0_75.jpg',12.82,'I am legend');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Bessel van der Kolk ', 4, '"The Body Keeps the Score" by Bessel van der Kolk is a groundbreaking exploration of trauma and its effects on the human body and mind. Drawing from his extensive experience as a psychiatrist and researcher, van der Kolk delves into the ways in which trauma can shape individuals, often leading to physical and psychological symptoms. Through compelling case studies and scientific insights, the book offers a comprehensive understanding of how trauma manifests itself and provides strategies for healing and recovery. It emphasizes the importance of addressing trauma not only through traditional therapy but also through alternative approaches such as yoga, EMDR, and neurofeedback. Ultimately, "The Body Keeps the Score" offers hope and guidance for those struggling to overcome the lasting impact of trauma.','https://m.media-amazon.com/images/I/71bVExi4yXL._AC_UF1000,1000_QL80_.jpg',33.00,'The body keeps the score');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Charles Duhigg ', 5, '"La dittatura delle abitudini" is a book by Charles Duhigg that explores the influence of habits in our lives and society. Duhigg highlights how habits shape our behavior, often in subtle and imperceptible ways. Through engaging stories and scientific research, the book examines how habits are formed, how they can be changed, and how they can impact personal and professional success. Duhigg also provides practical tools for identifying and modifying unwanted habits, empowering readers to take control of their own lives and destinies.','https://m.media-amazon.com/images/W/MEDIAX_849526-T1/images/I/71GigAO92UL._SY466_.jpg',15.06,'La dittatura delle abitudini');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Sigmund Freud ', 1, '"The Interpretation of Dreams" by Sigmund Freud is a seminal work in the field of psychology. In this book, Freud delves into the significance of dreams, arguing that they are a manifestation of unconscious desires and conflicts. He introduces the concept of the unconscious mind and explores how dreams serve as a pathway to understanding hidden aspects of the psyche. Freud\'s psychoanalytic approach to dream interpretation revolutionized the field of psychology, emphasizing the importance of symbolism and metaphor in understanding human behavior. Through detailed analysis of numerous case studies and his own dreams, Freud presents a comprehensive framework for interpreting dreams and unlocking their deeper meanings','https://m.media-amazon.com/images/I/714XmrShddL._SY466_.jpg',14.90,'L\'interpretazione dei sogni');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Giuliana Lupi ', 2, '"Il libro della psicologia. Grandi idee spiegate in modo semplice" is an accessible guide that explores the fundamental concepts of psychology in clear and understandable language. Through a straightforward and engaging approach, the book covers a wide range of topics, from the evolution of psychology as a scientific discipline to the theories and methodologies used in psychological research. Each topic is presented clearly and concisely, with illustrations and examples that help readers grasp complex concepts simply. With a particular focus on the practical applications of psychology in everyday life, this book is an excellent resource for anyone interested in gaining a better understanding of how the human mind works.','https://m.media-amazon.com/images/I/71nKh1RtZwL._SY466_.jpg',23.65,'Il libro della psicologia. Grandi idee spiegate in modo semplice');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Luca Gheno ', 3, '"Psicologia nera" is an exploration of the darker facets of the human mind. Through a series of cases and analyses, the author sheds light on the darkest recesses of the human psyche, examining phenomena such as manipulation, psychopathy, violence, and deviance. The book offers a chilling and captivating glimpse into the dark side of human nature, exploring the motives and mechanisms of disturbed and antisocial behavior. Through a combination of engaging storytelling and psychological insights, "Dark Psychology" provides a unique and often unsettling perspective on the human mind in its most troubling manifestations.','https://m.media-amazon.com/images/I/61KeJ47L0HL._SY466_.jpg',14.97,'Psicologia Nera');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Lisa Feldman Barrett ', 5, '"Come sono fatte le emozioni. La vita segreta del cervello" by Lisa Feldman Barrett is a groundbreaking exploration of the nature of emotions. Barrett challenges the traditional view of emotions as hardwired, preprogrammed reactions, instead presenting a compelling argument that emotions are constructed by the brain based on our past experiences, cultural context, and current situation. Drawing on the latest research in neuroscience and psychology, Barrett reveals the complex and dynamic process through which the brain creates emotions. She also explores the implications of this theory for our understanding of mental health, interpersonal relationships, and overall well-being. With accessible language and engaging storytelling, "How Emotions Are Made" offers readers a fascinating journey into the inner workings of the human mind and emotions.','https://m.media-amazon.com/images/I/611WMa73OiL._SY466_.jpg',38.00,'Come sono fatte le emozioni. La vita segreta del cervello');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Marguerite Yourcenar ', 3, '"Memorie di Adriano" by Marguerite Yourcenar is a fictionalized autobiography of the Roman Emperor Hadrian, presented as a series of letters written to his successor, Marcus Aurelius. Through these letters, Hadrian reflects on his life, achievements, and philosophical beliefs, offering insights into his reign and the challenges he faced. The novel delves into Hadrian\'s personal and political struggles, his relationships with key figures such as Antinous and Plotina, and his contemplation of mortality and legacy. Yourcenar\'s vivid prose and meticulous historical research bring the ancient world to life, providing readers with a rich and immersive portrait of one of Rome\'s most enigmatic leaders.','https://m.media-amazon.com/images/I/71Wbhgaqz7L._SY466_.jpg',12.82,'Memorie di Adriano');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Unione Editori e Librai Cattolici Italiani (UELCI)', 5, '"La sacra Bibbia" is a sacred text that tells the story of humanity and the relationship between God and humanity according to Jewish and Christian tradition. Divided into two main parts, the Old and New Testaments, it contains a wide range of literary genres including history, poetry, wisdom, prophets, and letters. The Old Testament recounts the creation of the world, the history of the Jewish people, divine laws, and the prophecies of the prophets, while the New Testament focuses on the life of Jesus Christ, his teachings, his death and resurrection, and the spread of Christianity through the teachings of the apostles. The Bible has exerted a profound and lasting influence on Western culture, religion, and literature and continues to be a source of inspiration and guidance for millions of people around the world.','https://www.lafeltrinelli.it/images/9791280736246_0_536_0_75.jpg',17.58,'La sacra Bibbia');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Sherman Alexie ', 5, '"Educazione indiana" by Sherman Alexie is a collection of autobiographical short stories that follows the journey of a Native American boy, Junior, as he navigates the challenges of growing up on the Spokane Indian Reservation. Through Junior\'s experiences, the book explores themes of identity, culture clash, and resilience in the face of adversity. Junior grapples with racism, poverty, and the legacy of colonialism while striving to find his place in the world. As he moves between the reservation school and the predominantly white school off the reservation, Junior confronts the complexities of straddling two worlds and wrestles with the conflicting expectations of his family, community, and society. With humor, honesty, and insight, "Indian Education" offers a poignant portrayal of the Native American experience and the universal struggles of adolescence.','https://www.lafeltrinelli.it/images/9788809971073_0_536_0_75.jpg',17.10,'Educazione indiana');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Marco Missiroli ', 1, '"Atti impuri" by Marco Missiroli is a novel that delves into the complexities of human relationships and desires. Set in contemporary Italy, the story revolves around the lives of three characters: Claudia, a middle-aged woman trapped in a loveless marriage; Andrea, a successful architect struggling with his own insecurities; and Margherita, a young student who becomes entangled in their lives. As their paths intertwine, the novel explores themes of passion, guilt, and the search for fulfillment. Through vivid prose and rich characterization, "Act of Impurity" offers a compelling exploration of the darker aspects of desire and the consequences of acting on it.','https://www.lafeltrinelli.it/images/9788858153444_0_536_0_75.jpg',12.35,'Atti impuri');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Simon Scarrow ', 2, '"Nel nome di Roma" is a historical novel by Steven Saylor set in ancient Rome during the period of the Republic. The plot follows the adventures of Gordianus, a private investigator known as the "Finder," who becomes entangled in intricate political and criminal intrigues while attempting to solve mysteries and murders in the capital of the Empire. Through his investigations, readers are immersed in the vibrant and chaotic atmosphere of ancient Rome, with detailed descriptions of daily life, customs, and traditions of the time. With a gripping plot and well-defined characters, "In the Name of Rome" offers an exciting exploration of the ancient world and its darkest secrets.','https://m.media-amazon.com/images/I/91GaA-ZnofL._SY466_.jpg',12.25,'Nel nome di Roma');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Matteo Strukul ', 3, 'Florence, 1429. Upon the death of the patriarch Giovanni de\' Medici, his sons Cosimo and Lorenzo find themselves at the helm of a true financial empire, yet, simultaneously, surrounded by sworn enemies like Rinaldo degli Albizzi and Palla Strozzi, representatives of the most powerful Florentine families. With intelligence and ruthlessness, the two brothers conquer political power, balancing a merciless sense of business with a love for art and culture. As work on the construction of the dome of Santa Maria del Fiore progresses under the direction of Filippo Brunelleschi, lifelong adversaries continue to weave their plots. Among them is also a woman of infinite beauty but cursed charm, capable of ensnaring a man\'s heart. Over the course of four years, after narrowly escaping a series of conspiracies, the plague, and the war against Lucca, Cosimo finds himself imprisoned, facing the death penalty. Amidst murders, betrayals, and palace intrigues, this novel narrates the saga of the most powerful family of the Renaissance, the beginning of their rise to the Florentine Signoria, amidst a whirlwind of intrigue and twists that feature unscrupulous condottieri, deadly poisoners, and bloodthirsty Swiss mercenaries.','https://www.scontolibri.com/pub/media/catalog/product/imgean/g/3/9/7/4/9788854194793g.jpg?width=700&height=1000&store=default&image-type=image',9.41,'I medici. Una dinastia al potere');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Sigmund Freud ', 4, '"Ossessioni, fobie e paranoia" is an in-depth exploration of the most common and debilitating psychological disorders that afflict individuals. Through a combination of clinical cases, psychological theories, and therapeutic approaches, the book provides a comprehensive overview of disorders such as obsessive-compulsive disorder, specific phobias, and paranoia. With concrete examples and clarifications on the causes and treatment modalities, the text offers a valuable resource for those seeking a better understanding of mental disorders and how to address them. With accessible language and a compassionate approach, "Obsessions, Phobias, and Paranoia" provides an informative and reassuring guide for those facing these challenges in their own lives or in a professional setting.','https://www.lafeltrinelli.it/images/9788854174535_0_536_0_75.jpg',3.92,'Ossessioni, fobie e paranoia');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('James Clear ', 3, '"Atomic habits. Piccole abitudini per grandi cambiamenti" by James Clear is a practical guide to building good habits and breaking bad ones. Clear introduces the concept of atomic habits, which are small, incremental changes that lead to significant improvements over time. Through engaging stories, scientific research, and actionable advice, Clear explains how habits shape our lives and provides a framework for creating positive habits that stick. Whether you want to improve your health, productivity, or relationships, "Atomic Habits" offers practical strategies for making lasting changes and achieving your goals.','https://www.lafeltrinelli.it/images/9791221208870_0_536_0_75.jpg',16.06,'Atomic habits. Piccole abitudini per grandi cambiamenti');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Nikki St. Crowe ', 4, '"The Never King" by Nikki St. Crowe is a fantasy adventure following the journey of a young hero named Lannick deVeers. In a world ruled by a tyrannical ruler known as the Never King, Lannick finds himself caught up in a rebellion to overthrow the oppressive regime. As he faces deadly dangers and political intrigue, Lannick must summon the courage to fight for freedom and the fate of his people. With compelling storytelling and engaging characters, "The Never King" offers an epic journey through a world of magic, mystery, and adventure.','https://www.lafeltrinelli.it/images/9788804771210_0_536_0_75.jpg',13.30,'The never king');
INSERT INTO db_final_library.books(author, rating, description, photo, price, title)VALUES('Arató András', 2, '"La politica pop online" analyzes the impact of new media and digital platforms on contemporary politics. Through a series of case studies and in-depth analysis, the author explores how the internet and social media have transformed the way political campaigns are conducted, influenced public opinion, and shaped the political landscape. From the phenomenon of political memes to the spread of online misinformation and manipulation, the book offers a comprehensive overview of the challenges and opportunities presented by digital politics. With a critical and informed perspective, "The Pop Politics Online" provides a thorough analysis of how politics and communication have evolved in the digital age.','https://www.lafeltrinelli.it/images/9788815285263_0_536_0_75.jpg',12.35,'La politica pop online');


--import client purchases--
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 5, '2024-01-24',1 );
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 15, '2024-01-24', 2 );
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 2, '2024-01-24', 1 );
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 31, '2024-01-24',2);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 14, '2024-01-20', 4);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 29, '2024-01-19', 5);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 539, '2023-02-18',10);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 340, '2023-04-15',9);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 15, '2024-01-26',8);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 272, '2023-11-25',11);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 684, '2023-08-07',14);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 150, '2024-01-30',14);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 350, '2023-09-10',6);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 150, '2024-01-20',13);
INSERT INTO db_final_library.client_purchases(amount, `date`, book_id)VALUES( 450, '2023-01-20',7);



--import categories--
INSERT INTO db_final_library.categories( name)VALUES('Bambini e Ragazzi');
INSERT INTO db_final_library.categories( name)VALUES('Gialli e Thriller');
INSERT INTO db_final_library.categories( name)VALUES('Narrativa Straniera');
INSERT INTO db_final_library.categories( name)VALUES('Fantasia e Fantascienza');
INSERT INTO db_final_library.categories( name)VALUES('Religione e Spiritualità');
INSERT INTO db_final_library.categories( name)VALUES('Psicologia');
INSERT INTO db_final_library.categories( name)VALUES('Storico');
INSERT INTO db_final_library.categories( name)VALUES('Informatico');
INSERT INTO db_final_library.categories( name)VALUES('Horror');
INSERT INTO db_final_library.categories( name)VALUES('Distopico');
INSERT INTO db_final_library.categories( name)VALUES('Umoristico');
-

--import categories-books--
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 1);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(4, 2);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(1, 2);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(4, 3);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(1, 3);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(4, 4);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(1, 4);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(4, 5);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(1, 5);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(8, 6);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(10, 7);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 7);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(4, 8);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(1, 8);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(4, 9);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(1, 9);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(4, 10);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(1, 10);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 11);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(1, 11);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 12);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(1, 12);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(2, 13);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 13);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 14);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(10, 14);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 15);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(9, 15);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(9, 16);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 16);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(9, 17);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 17);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(9, 18);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 18);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(9, 19);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 19);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(9, 20);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 20);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(9, 21);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(3, 21);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(6, 22);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(6, 23);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(6, 24);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(6, 25);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(6, 26);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(6, 27);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(7, 28);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(5, 29);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(5, 30);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(5, 31);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(7, 32);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(7, 33);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(6, 34);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(6, 35);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(9, 36);
INSERT INTO db_final_library.categories_book_list(category_list_id, book_list_id)VALUES(11, 37);





--import supplier--
INSERT INTO db_final_library.suppliers(name)VALUES('Mondadori');
INSERT INTO db_final_library.suppliers(name)VALUES('Feltrinelli');
INSERT INTO db_final_library.suppliers(name)VALUES('Fabbri');
INSERT INTO db_final_library.suppliers(name)VALUES('Penguin');
INSERT INTO db_final_library.suppliers(name)VALUES('Giunti');
INSERT INTO db_final_library.suppliers(name)VALUES('Einaudi');
INSERT INTO db_final_library.suppliers(name)VALUES('Bompiani');


--import supplier-book-purchases --
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(50, '2023-12-20', 399, 2, 1);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(70, '2023-12-10', 588.6, 1, 1);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(50, '2023-12-13', 325, 1, 1);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(149, '2023-12-11', 1189.02, 2, 1);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(59, '2023-12-29', 500, 3, 2);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(43, '2023-12-29', 499, 4, 3);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(68, '2023-12-29', 589.3, 5, 4);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(75, '2023-11-11', 689.45, 6, 5);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(35, '2023-08-29', 419.65, 7, 7);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(48, '2023-07-22', 547.2, 14, 2);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(97, '2023-12-29', 863.3, 11, 3);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(66, '2023-03-12', 920.7, 10, 5);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(15, '2023-12-01', 142.25, 8, 4);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(47, '2023-05-10', 691.84, 13, 2);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(140,'2023-02-28', 4186, 12, 1);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(65,'2023-04-12', 1166.75, 15, 4);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(182,'2023-03-17', 3112.2, 16, 3);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(79,'2023-09-11', 442.4, 17, 1);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(58,'2023-12-22',468.64 , 18, 7);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(100,'2023-01-28',1490 , 19, 5);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(172,'2022-12-30',2562.8 , 20, 6);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(200,'2023-02-28', 2564, 21, 2);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(40,'2023-03-28',1320 , 22, 3);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(44,'2024-01-29', 662.64, 23, 4);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(71,'2023-07-22',1057.9 , 24, 7);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(79,'2023-05-10',1868.35 , 25, 1);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(89,'2023-07-20', 1332.33, 26, 4);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(122,'2022-12-27',4636 , 27, 2);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(70,'2022-12-15',897.4 , 28, 1);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(80,'2022-12-11',1406.4 , 29, 5);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(100,'2022-11-11',1710 , 30, 4);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(120,'2022-11-19',1482 , 31, 2);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(150,'2022-11-26',1837.5 , 32, 6);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(132,'2023-06-27',1242.12 , 33, 2);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(132,'2023-05-25',1755.6 , 36, 2);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(140,'2022-12-27',548.8 , 34, 3);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(60,'2022-06-27',963.6 , 35, 1);
INSERT INTO db_final_library.supplier_book_purchases(amount, `date`, price, book_id, supplier_id)VALUES(10,'2023-12-30',123.5 , 37, 1);



-- import users
INSERT INTO db_final_library.`role`(name)VALUES('ADMIN');
INSERT INTO db_final_library.`role`(name)VALUES('USER');

INSERT INTO db_final_library.library_user(email, first_name, last_name, password)VALUES('anna@gmail.com', 'Anna', 'Rossi', '{noop}anna');
INSERT INTO db_final_library.library_user(email, first_name, last_name, password)VALUES('giulio@gmail.com', 'Giulio', 'Rossi', '{noop}giulio');

INSERT INTO db_final_library.library_user_role_set(library_user_id, role_set_name)VALUES(1, 'ADMIN');
INSERT INTO db_final_library.library_user_role_set(library_user_id, role_set_name)VALUES(1, 'USER');
INSERT INTO db_final_library.library_user_role_set(library_user_id, role_set_name)VALUES(2, 'USER');